using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using NZBPlanetApiJSON;
//
//    var nzBplanet = NzBplanet.FromJson(jsonString);

namespace Showlist2026.NZBPlanetApiJSON
{
    public partial class NzBplanetJSON
    {
        [JsonProperty("@attributes")]
        public NzBplanetAttributes Attributes { get; set; }

        [JsonProperty("channel")]
        public Channel Channel { get; set; }

    }

    public partial class NzBplanetAttributes
    {
        [JsonProperty("version")]
        public string Version { get; set; }
    }

    public partial class Channel
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("link")]
        public Uri Link { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        //[JsonProperty("webMaster")]
        //public string WebMaster { get; set; }

        //[JsonProperty("category")]
        //public List<string> Category { get; set; }

        //[JsonProperty("image")]
        //public Image Image { get; set; }

        //[JsonProperty("response")]
        //public Response Response { get; set; }

        [JsonProperty("item")]
        public List<Item> Item { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("link")]
        public Uri Link { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class Item
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("guid")]
        public Uri Guid { get; set; }

        [JsonProperty("link")]
        public Uri Link { get; set; }

        [JsonProperty("comments")]
        public Uri Comments { get; set; }

        [JsonProperty("pubDate")]
        public string PubDate { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("enclosure")]
        public Enclosure Enclosure { get; set; }

        [JsonProperty("attr")]
        public List<Attr> Attr { get; set; }


        // Create a key that can be used to order shows by manual preference
        public int Sortkey
        {
            get
            {
                int s = 0;
                if (Category.ToLower().Contains("foreign"))
                {
                    s = 500;
                }
                if (Category.EndsWith("SD"))
                {
                    if (Title.ToLower().Contains("x264") || Title.ToLower().Contains("x265"))
                    {
                        return s+10;
                    }
                    return s + 20;
                }

                if(Title.ToLower().Contains("x265"))
                {
                    return s + 30;
                }
                if (SizeAsNumberMBs < 501)
                {
                    return s + 40;
                }

                return SizeAsNumberMBs + s + 10000;
            }
        }

        public int SizeAsNumber
        {
            get
            {
                int x = 0;
                bool ok = int.TryParse(Size, out x);
                if (ok)
                {
                    return x;
                }
                return int.MaxValue;
            }
        }
        public int SizeAsNumberMBs
        {
            get
            {
                return (int)Math.Round((decimal)SizeAsNumber / 1024 / 1024, 0);
            }
        }


        // Some methods to get the attributes without needing to code it all over the place
        public string Size
        {
            get
            {
                return GetAttr(Name.Size);
            }
        }
        public string Season
        {
            get
            {
                return GetAttr(Name.Season)??"";
            }
        }
        public string Episode
        {
            get
            {
                return GetAttr(Name.Episode)??"";
            }
        }
        public string GetAttr(Name name)
        {
             return Attr.FirstOrDefault(a => a.Attributes.Name == name)?.Attributes?.Value;
        }

        public string EpNumberFormatted
        {
            get
            {
                return $"{Season}{Episode}";
            }
        }

    }

    public partial class Attr
    {
        [JsonProperty("@attributes")]
        public AttrAttributes Attributes { get; set; }
    }

    public partial class AttrAttributes
    {
        [JsonProperty("name")]
        public Name Name { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }
    }

    public partial class Enclosure
    {
        [JsonProperty("@attributes")]
        public EnclosureAttributes Attributes { get; set; }
    }

    public partial class EnclosureAttributes
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("length")]
        public string Length { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class Response
    {
        [JsonProperty("@attributes")]
        public ResponseAttributes Attributes { get; set; }
    }

    public partial class ResponseAttributes
    {
        [JsonProperty("offset")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Offset { get; set; }

        [JsonProperty("total")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Total { get; set; }
    }

    public enum Name { Category, Comments, Episode, Grabs, Imdb, Password, Season, Size, Tvairdate, Tvtitle, Usenetdate };

    public enum TypeEnum { ApplicationXNzb };

    public partial class NzBplanet
    {
        public static NzBplanet FromJson(string json) => JsonConvert.DeserializeObject<NzBplanet>(json, NZBPlanetApiJSON.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this NzBplanet self) => JsonConvert.SerializeObject(self, NZBPlanetApiJSON.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                NameConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class NameConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Name) || t == typeof(Name?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "category":
                    return Name.Category;
                case "comments":
                    return Name.Comments;
                case "episode":
                    return Name.Episode;
                case "grabs":
                    return Name.Grabs;
                case "imdb":
                    return Name.Imdb;
                case "password":
                    return Name.Password;
                case "season":
                    return Name.Season;
                case "size":
                    return Name.Size;
                case "tvairdate":
                    return Name.Tvairdate;
                case "tvtitle":
                    return Name.Tvtitle;
                case "usenetdate":
                    return Name.Usenetdate;
            }
            throw new Exception("Cannot unmarshal type Name");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Name)untypedValue;
            switch (value)
            {
                case Name.Category:
                    serializer.Serialize(writer, "category");
                    return;
                case Name.Comments:
                    serializer.Serialize(writer, "comments");
                    return;
                case Name.Episode:
                    serializer.Serialize(writer, "episode");
                    return;
                case Name.Grabs:
                    serializer.Serialize(writer, "grabs");
                    return;
                case Name.Imdb:
                    serializer.Serialize(writer, "imdb");
                    return;
                case Name.Password:
                    serializer.Serialize(writer, "password");
                    return;
                case Name.Season:
                    serializer.Serialize(writer, "season");
                    return;
                case Name.Size:
                    serializer.Serialize(writer, "size");
                    return;
                case Name.Tvairdate:
                    serializer.Serialize(writer, "tvairdate");
                    return;
                case Name.Tvtitle:
                    serializer.Serialize(writer, "tvtitle");
                    return;
                case Name.Usenetdate:
                    serializer.Serialize(writer, "usenetdate");
                    return;
            }
            throw new Exception("Cannot marshal type Name");
        }

        public static readonly NameConverter Singleton = new NameConverter();
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
