// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Showlist2026.Data;

#nullable disable

namespace Showlist2026.Data.Migrations
{
    [DbContext(typeof(ShowlistDbContext))]
    [Migration("20260321100000_AddUserGivenUpSelectionTable")]
    partial class AddUserGivenUpSelectionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Showlist2026.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppSetting");
                });

            modelBuilder.Entity("Showlist2026.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Showlist2026.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AirDateOffset2")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("airdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("airtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("episodeid")
                        .HasColumnType("bigint");

                    b.Property<string>("imagemedium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageoriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("links")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("number")
                        .HasColumnType("bigint");

                    b.Property<string>("runtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("season")
                        .HasColumnType("bigint");

                    b.Property<int?>("showId")
                        .HasColumnType("int");

                    b.Property<string>("summary")
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("showId");

                    b.ToTable("Episode");
                });

            modelBuilder.Entity("Showlist2026.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("genretextId")
                        .HasColumnType("int");

                    b.Property<int?>("showId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("genretextId");

                    b.HasIndex("showId");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("Showlist2026.Entities.GenreText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("genre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GenreText");
                });

            modelBuilder.Entity("Showlist2026.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Showlist2026.Entities.Network", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("networkid")
                        .HasColumnType("bigint");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tzId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("countryId");

                    b.HasIndex("tzId");

                    b.ToTable("Network");
                });

            modelBuilder.Entity("Showlist2026.Entities.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LanguagesId")
                        .HasColumnType("int");

                    b.Property<int?>("NetworksId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShowUpdatedsId")
                        .HasColumnType("int");

                    b.Property<int?>("TypesId")
                        .HasColumnType("int");

                    b.Property<int?>("WebNetworksId")
                        .HasColumnType("int");

                    b.Property<string>("imagemed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageorig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imdb")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("needsupdate")
                        .HasColumnType("bit");

                    b.Property<long>("page")
                        .HasColumnType("bigint");

                    b.Property<string>("premiered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scheduledays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scheduletime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("showid")
                        .HasColumnType("bigint");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thetvdb")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("tvrage")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguagesId");

                    b.HasIndex("NetworksId");

                    b.HasIndex("ShowUpdatedsId");

                    b.HasIndex("TypesId");

                    b.HasIndex("WebNetworksId");

                    b.ToTable("Show");
                });

            modelBuilder.Entity("Showlist2026.Entities.ShowUpdated", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("lastupdateprocessed")
                        .HasColumnType("bit");

                    b.Property<long>("showudatedid")
                        .HasColumnType("bigint");

                    b.Property<long>("updatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<long>("xshowid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ShowUpdated");
                });

            modelBuilder.Entity("Showlist2026.Entities.TVDirectories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysToScan")
                        .HasColumnType("int");

                    b.Property<string>("Filter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinFileSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TVDirectories");
                });

            modelBuilder.Entity("Showlist2026.Entities.TVSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("URLTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TVSites");
                });

            modelBuilder.Entity("Showlist2026.Entities.Timezone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("UTCDSTOffset")
                        .HasColumnType("float");

                    b.Property<double>("UTCOffset")
                        .HasColumnType("float");

                    b.Property<string>("countrycode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Timezone");
                });

            modelBuilder.Entity("Showlist2026.Entities.TouchFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FileDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasRealFile")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Touchfile");
                });

            modelBuilder.Entity("Showlist2026.Entities.TouchFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FileDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Touchfolder");
                });

            modelBuilder.Entity("Showlist2026.Entities.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserCountrySelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("countryId")
                        .HasColumnType("int");

                    b.Property<bool>("include")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("countryId");

                    b.ToTable("UserCountrySelection");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserGivenUpSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("GivenUpDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("episodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("episodeId");

                    b.ToTable("UserGivenUpSelection");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserGenreSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("genretextId")
                        .HasColumnType("int");

                    b.Property<bool>("include")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("genretextId");

                    b.ToTable("UserGenreSelection");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserLanguageSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("include")
                        .HasColumnType("bit");

                    b.Property<int>("languageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("languageId");

                    b.ToTable("UserLanguageSelection");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserNetworkSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("include")
                        .HasColumnType("bit");

                    b.Property<int>("networkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("networkId");

                    b.ToTable("UserNetworkSelection");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserShowSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<bool>("include")
                        .HasColumnType("bit");

                    b.Property<int>("showId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("showId");

                    b.ToTable("UserShowSelection");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserTypeSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("include")
                        .HasColumnType("bit");

                    b.Property<int>("typeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("typeId");

                    b.ToTable("UserTypeSelection");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserWatchedSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("episodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("episodeId");

                    b.ToTable("UserWatchedSelection");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserWebNetworkSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("include")
                        .HasColumnType("bit");

                    b.Property<int>("webnetworkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("webnetworkId");

                    b.ToTable("UserWebNetworkSelection");
                });

            modelBuilder.Entity("Showlist2026.Entities.WatchedHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("WatchedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("episodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("episodeId");

                    b.ToTable("WatchedHistory");
                });

            modelBuilder.Entity("Showlist2026.Entities.WebNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tzId")
                        .HasColumnType("int");

                    b.Property<long>("webid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("countryId");

                    b.HasIndex("tzId");

                    b.ToTable("WebNetwork");
                });

            modelBuilder.Entity("Showlist2026.Entities.Episode", b =>
                {
                    b.HasOne("Showlist2026.Entities.Show", "show")
                        .WithMany("Episodes")
                        .HasForeignKey("showId");

                    b.Navigation("show");
                });

            modelBuilder.Entity("Showlist2026.Entities.Genre", b =>
                {
                    b.HasOne("Showlist2026.Entities.GenreText", "genretext")
                        .WithMany("Genres")
                        .HasForeignKey("genretextId");

                    b.HasOne("Showlist2026.Entities.Show", "show")
                        .WithMany("Genres")
                        .HasForeignKey("showId");

                    b.Navigation("genretext");

                    b.Navigation("show");
                });

            modelBuilder.Entity("Showlist2026.Entities.Network", b =>
                {
                    b.HasOne("Showlist2026.Entities.Country", "country")
                        .WithMany()
                        .HasForeignKey("countryId");

                    b.HasOne("Showlist2026.Entities.Timezone", "tz")
                        .WithMany()
                        .HasForeignKey("tzId");

                    b.Navigation("country");

                    b.Navigation("tz");
                });

            modelBuilder.Entity("Showlist2026.Entities.Show", b =>
                {
                    b.HasOne("Showlist2026.Entities.Language", "Languages")
                        .WithMany()
                        .HasForeignKey("LanguagesId");

                    b.HasOne("Showlist2026.Entities.Network", "Networks")
                        .WithMany()
                        .HasForeignKey("NetworksId");

                    b.HasOne("Showlist2026.Entities.ShowUpdated", "ShowUpdateds")
                        .WithMany()
                        .HasForeignKey("ShowUpdatedsId");

                    b.HasOne("Showlist2026.Entities.Type", "Types")
                        .WithMany()
                        .HasForeignKey("TypesId");

                    b.HasOne("Showlist2026.Entities.WebNetwork", "WebNetworks")
                        .WithMany()
                        .HasForeignKey("WebNetworksId");

                    b.Navigation("Languages");

                    b.Navigation("Networks");

                    b.Navigation("ShowUpdateds");

                    b.Navigation("Types");

                    b.Navigation("WebNetworks");
                });

            modelBuilder.Entity("Showlist2026.Entities.TouchFile", b =>
                {
                    b.HasOne("Showlist2026.Entities.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserCountrySelection", b =>
                {
                    b.HasOne("Showlist2026.Entities.Country", "country")
                        .WithMany("UserCountrySelections")
                        .HasForeignKey("countryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserGivenUpSelection", b =>
                {
                    b.HasOne("Showlist2026.Entities.Episode", "episode")
                        .WithMany()
                        .HasForeignKey("episodeId");

                    b.Navigation("episode");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserGenreSelection", b =>
                {
                    b.HasOne("Showlist2026.Entities.GenreText", "genretext")
                        .WithMany("UserGenreSelections")
                        .HasForeignKey("genretextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("genretext");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserLanguageSelection", b =>
                {
                    b.HasOne("Showlist2026.Entities.Language", "language")
                        .WithMany("UserLanguageSelections")
                        .HasForeignKey("languageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("language");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserNetworkSelection", b =>
                {
                    b.HasOne("Showlist2026.Entities.Network", "network")
                        .WithMany("UserNetworkSelections")
                        .HasForeignKey("networkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("network");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserShowSelection", b =>
                {
                    b.HasOne("Showlist2026.Entities.Show", "show")
                        .WithMany("UserShowSelections")
                        .HasForeignKey("showId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("show");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserTypeSelection", b =>
                {
                    b.HasOne("Showlist2026.Entities.Type", "type")
                        .WithMany("UserTypeSelections")
                        .HasForeignKey("typeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("type");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserWatchedSelection", b =>
                {
                    b.HasOne("Showlist2026.Entities.Episode", "episode")
                        .WithMany("UserWatchedSelections")
                        .HasForeignKey("episodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("episode");
                });

            modelBuilder.Entity("Showlist2026.Entities.UserWebNetworkSelection", b =>
                {
                    b.HasOne("Showlist2026.Entities.WebNetwork", "webnetwork")
                        .WithMany("UserWebNetworkSelections")
                        .HasForeignKey("webnetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("webnetwork");
                });

            modelBuilder.Entity("Showlist2026.Entities.WatchedHistory", b =>
                {
                    b.HasOne("Showlist2026.Entities.Episode", "episode")
                        .WithMany()
                        .HasForeignKey("episodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("episode");
                });

            modelBuilder.Entity("Showlist2026.Entities.WebNetwork", b =>
                {
                    b.HasOne("Showlist2026.Entities.Country", "country")
                        .WithMany()
                        .HasForeignKey("countryId");

                    b.HasOne("Showlist2026.Entities.Timezone", "tz")
                        .WithMany()
                        .HasForeignKey("tzId");

                    b.Navigation("country");

                    b.Navigation("tz");
                });

            modelBuilder.Entity("Showlist2026.Entities.Country", b =>
                {
                    b.Navigation("UserCountrySelections");
                });

            modelBuilder.Entity("Showlist2026.Entities.Episode", b =>
                {
                    b.Navigation("UserWatchedSelections");
                });

            modelBuilder.Entity("Showlist2026.Entities.GenreText", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("UserGenreSelections");
                });

            modelBuilder.Entity("Showlist2026.Entities.Language", b =>
                {
                    b.Navigation("UserLanguageSelections");
                });

            modelBuilder.Entity("Showlist2026.Entities.Network", b =>
                {
                    b.Navigation("UserNetworkSelections");
                });

            modelBuilder.Entity("Showlist2026.Entities.Show", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Genres");

                    b.Navigation("UserShowSelections");
                });

            modelBuilder.Entity("Showlist2026.Entities.Type", b =>
                {
                    b.Navigation("UserTypeSelections");
                });

            modelBuilder.Entity("Showlist2026.Entities.WebNetwork", b =>
                {
                    b.Navigation("UserWebNetworkSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
