// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Showlist2026.Data;

#nullable disable

namespace Showlist2026.Data.Migrations
{
    [DbContext(typeof(ShowlistDbContext))]
    [Migration("20260608112622_AddShowLinks")]
    partial class AddShowLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Showlist2026.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppSetting");
                });

            modelBuilder.Entity("Showlist2026.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Wanted")
                        .HasColumnType("bit");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Showlist2026.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AirDateOffset2")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("GivenUp")
                        .HasColumnType("bit");

                    b.Property<bool>("Watched")
                        .HasColumnType("bit");

                    b.Property<string>("airdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("airtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("episodeid")
                        .HasColumnType("bigint");

                    b.Property<string>("imagemedium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageoriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("links")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("number")
                        .HasColumnType("bigint");

                    b.Property<string>("runtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("season")
                        .HasColumnType("bigint");

                    b.Property<int?>("showId")
                        .HasColumnType("int");

                    b.Property<string>("summary")
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("showId");

                    b.ToTable("Episode");
                });

            modelBuilder.Entity("Showlist2026.Entities.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FolderPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Friend");
                });

            modelBuilder.Entity("Showlist2026.Entities.FriendCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CopiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FriendId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.ToTable("FriendCopy");
                });

            modelBuilder.Entity("Showlist2026.Entities.FriendShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FriendId")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("ShowId");

                    b.ToTable("FriendShow");
                });

            modelBuilder.Entity("Showlist2026.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("genretextId")
                        .HasColumnType("int");

                    b.Property<int?>("showId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("genretextId");

                    b.HasIndex("showId");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("Showlist2026.Entities.GenreText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Wanted")
                        .HasColumnType("bit");

                    b.Property<string>("genre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GenreText");
                });

            modelBuilder.Entity("Showlist2026.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Wanted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Showlist2026.Entities.Network", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Wanted")
                        .HasColumnType("bit");

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("networkid")
                        .HasColumnType("bigint");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tzId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("countryId");

                    b.HasIndex("tzId");

                    b.ToTable("Network");
                });

            modelBuilder.Entity("Showlist2026.Entities.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LanguagesId")
                        .HasColumnType("int");

                    b.Property<int?>("NetworksId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("TypesId")
                        .HasColumnType("int");

                    b.Property<bool?>("Wanted")
                        .HasColumnType("bit");

                    b.Property<int?>("WebNetworksId")
                        .HasColumnType("int");

                    b.Property<string>("imagemed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageorig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imdb")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("needsupdate")
                        .HasColumnType("bit");

                    b.Property<long>("page")
                        .HasColumnType("bigint");

                    b.Property<string>("premiered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scheduledays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scheduletime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("showid")
                        .HasColumnType("bigint");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thetvdb")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("tvrage")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguagesId");

                    b.HasIndex("NetworksId");

                    b.HasIndex("TypesId");

                    b.HasIndex("WebNetworksId");

                    b.ToTable("Show");
                });

            modelBuilder.Entity("Showlist2026.Entities.ShowFolderAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AliasName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SeasonOffset")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.ToTable("ShowFolderAliases");
                });

            modelBuilder.Entity("Showlist2026.Entities.ShowLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PredecessorShowId")
                        .HasColumnType("int");

                    b.Property<int>("SuccessorShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredecessorShowId");

                    b.HasIndex("SuccessorShowId");

                    b.ToTable("ShowLink");
                });

            modelBuilder.Entity("Showlist2026.Entities.TVDirectories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aliasable")
                        .HasColumnType("bit");

                    b.Property<int>("DaysToScan")
                        .HasColumnType("int");

                    b.Property<string>("Filter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinFileSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TVDirectories");
                });

            modelBuilder.Entity("Showlist2026.Entities.TVSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ApiBaseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RssApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RssBaseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URLTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TVSites");
                });

            modelBuilder.Entity("Showlist2026.Entities.Timezone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("UTCDSTOffset")
                        .HasColumnType("float");

                    b.Property<double>("UTCOffset")
                        .HasColumnType("float");

                    b.Property<string>("countrycode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Timezone");
                });

            modelBuilder.Entity("Showlist2026.Entities.TouchFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FileDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasRealFile")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Touchfile");
                });

            modelBuilder.Entity("Showlist2026.Entities.TouchFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FileDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Touchfolder");
                });

            modelBuilder.Entity("Showlist2026.Entities.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Wanted")
                        .HasColumnType("bit");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("Showlist2026.Entities.WebNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Wanted")
                        .HasColumnType("bit");

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tzId")
                        .HasColumnType("int");

                    b.Property<long>("webid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("countryId");

                    b.HasIndex("tzId");

                    b.ToTable("WebNetwork");
                });

            modelBuilder.Entity("Showlist2026.Entities.Episode", b =>
                {
                    b.HasOne("Showlist2026.Entities.Show", "show")
                        .WithMany("Episodes")
                        .HasForeignKey("showId");

                    b.Navigation("show");
                });

            modelBuilder.Entity("Showlist2026.Entities.FriendCopy", b =>
                {
                    b.HasOne("Showlist2026.Entities.Friend", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");
                });

            modelBuilder.Entity("Showlist2026.Entities.FriendShow", b =>
                {
                    b.HasOne("Showlist2026.Entities.Friend", "Friend")
                        .WithMany("InterestedShows")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Showlist2026.Entities.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Showlist2026.Entities.Genre", b =>
                {
                    b.HasOne("Showlist2026.Entities.GenreText", "genretext")
                        .WithMany("Genres")
                        .HasForeignKey("genretextId");

                    b.HasOne("Showlist2026.Entities.Show", "show")
                        .WithMany("Genres")
                        .HasForeignKey("showId");

                    b.Navigation("genretext");

                    b.Navigation("show");
                });

            modelBuilder.Entity("Showlist2026.Entities.Network", b =>
                {
                    b.HasOne("Showlist2026.Entities.Country", "country")
                        .WithMany()
                        .HasForeignKey("countryId");

                    b.HasOne("Showlist2026.Entities.Timezone", "tz")
                        .WithMany()
                        .HasForeignKey("tzId");

                    b.Navigation("country");

                    b.Navigation("tz");
                });

            modelBuilder.Entity("Showlist2026.Entities.Show", b =>
                {
                    b.HasOne("Showlist2026.Entities.Language", "Languages")
                        .WithMany()
                        .HasForeignKey("LanguagesId");

                    b.HasOne("Showlist2026.Entities.Network", "Networks")
                        .WithMany()
                        .HasForeignKey("NetworksId");

                    b.HasOne("Showlist2026.Entities.Type", "Types")
                        .WithMany()
                        .HasForeignKey("TypesId");

                    b.HasOne("Showlist2026.Entities.WebNetwork", "WebNetworks")
                        .WithMany()
                        .HasForeignKey("WebNetworksId");

                    b.Navigation("Languages");

                    b.Navigation("Networks");

                    b.Navigation("Types");

                    b.Navigation("WebNetworks");
                });

            modelBuilder.Entity("Showlist2026.Entities.ShowFolderAlias", b =>
                {
                    b.HasOne("Showlist2026.Entities.Show", "Show")
                        .WithMany("FolderAliases")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Showlist2026.Entities.ShowLink", b =>
                {
                    b.HasOne("Showlist2026.Entities.Show", "PredecessorShow")
                        .WithMany()
                        .HasForeignKey("PredecessorShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Showlist2026.Entities.Show", "SuccessorShow")
                        .WithMany()
                        .HasForeignKey("SuccessorShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PredecessorShow");

                    b.Navigation("SuccessorShow");
                });

            modelBuilder.Entity("Showlist2026.Entities.TouchFile", b =>
                {
                    b.HasOne("Showlist2026.Entities.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Showlist2026.Entities.WebNetwork", b =>
                {
                    b.HasOne("Showlist2026.Entities.Country", "country")
                        .WithMany()
                        .HasForeignKey("countryId");

                    b.HasOne("Showlist2026.Entities.Timezone", "tz")
                        .WithMany()
                        .HasForeignKey("tzId");

                    b.Navigation("country");

                    b.Navigation("tz");
                });

            modelBuilder.Entity("Showlist2026.Entities.Friend", b =>
                {
                    b.Navigation("InterestedShows");
                });

            modelBuilder.Entity("Showlist2026.Entities.GenreText", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Showlist2026.Entities.Show", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("FolderAliases");

                    b.Navigation("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
